Update WF_render_puml_in_PNG.yml

diff --git a/.github/workflows/WF_render_puml_in_PNG.yml b/.github/workflows/WF_render_puml_in_PNG.yml
--- a/.github/workflows/WF_render_puml_in_PNG.yml
+++ b/.github/workflows/WF_render_puml_in_PNG.yml
@@ -39,13 +39,13 @@ jobs:
       - name: Debug - Visualizza contenuto file .puml
         run: |
           echo "Checking content of PlantUML file:"
-          cat DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml || { echo "File not found!"; exit 1; }
+          cat DCC_Trasporti_H/puml_FNTB_Equipment_Cycle_Sub.puml || { echo "File not found!"; exit 1; }
 
       # Step 5.1: Cleanup previous PNG files
       - name: Cleanup previous PNG files
         run: |
           echo "Cleaning up old PNG files in output directory..."
-          find DCC_Trasporti_H/ -type f -name "FNTB_Equipment_Cycle_Sub*.png" -exec rm -f {} \;
+          find DCC_Trasporti_H/ -type f -name "puml_FNTB_Equipment_Cycle_Sub*.png" -exec rm -f {} \;
           echo "Old PNG files removed."
 
       # Step 6: Render PlantUML Diagram
@@ -53,7 +53,7 @@ jobs:
         run: |
           mkdir -p DCC_Trasporti_H/ # Assicura che la directory esista
           echo "Rendering PlantUML file..."
-          java -jar tools/plantuml.jar -tpng DCC_Trasporti_H/FNTB_Equipment_Cycle_Sub.puml || {
+          java -jar tools/plantuml.jar -tpng DCC_Trasporti_H/puml_FNTB_Equipment_Cycle_Sub.puml || {
             echo "PlantUML rendering failed! Checking tools and output directory:"
             ls -l tools
             ls -l DCC_Trasporti_H/
